### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by AlexisJW** [dfsalam/to-do-list#2]
Hello [dfsalam](https://github.com/dfsalam) 👋🏽

Good job working on the project so far!
✔️ Your project is well documented
✔️ App works as expected

Highlights 🎯

✔️ Descriptive PR
✔️ Set up app with webpack 📌
✔️ Good commit history

You can also consider:
    You have linter errors, to fix the error, please can you try this command: 'npm install html-webpack-plugin'.
    Once the plugin is installed, you will need to configure it in your webpack configuration file, You can import and use the  plugin like this:   `const HtmlWebpackPlugin = require('html-webpack-plugin');`

`module.exports = {
  // ...
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: './index.html',
    }),
  ],
  // ...
};`

**Comment by dfsalam** [comment]
### Thank you for your comments. 🔥 🔥
